#!/bin/sh

case $TERM in
screen*)
	TERMCAP="screen|VT 100/ANSI X3.64 virtual terminal:"'\
		:am:bs:km:mi:ms:pt:xn:\
		:co#80:it#8:li#24:\
		:AL=\E[%dL:DC=\E[%dP:DL=\E[%dM:DO=\E[%dB:IC=\E[%d@:\
		:LE=\E[%dD:RI=\E[%dC:SF=\E[%dS:UP=\E[%dA:ae=^O:al=\E[L:\
		:as=^N:bl=^G:bt=\E[Z:cd=\E[J:ce=\E[K:cl=\E[H\E[J:\
		:cm=\E[%i%d;%dH:cr=\r:cs=\E[%i%d;%dr:ct=\E[3g:dc=\E[P:\
		:dl=\E[M:do=\n:ei=\E[4l:ho=\E[H:im=\E[4h:is=\E)0:k1=\EOP:\
		:k2=\EOQ:k3=\EOR:k4=\EOS:k5=\E[15~:k6=\E[17~:k7=\E[18~:\
		:k8=\E[19~:k9=\E[20~:kD=\E[3~:kI=\E[2~:kN=\E[6~:kP=\E[5~:\
		:kb=\177:kd=\EOB:ke=\E[?1l\E>:kh=\E[1~:kl=\EOD:kr=\EOC:\
		:ks=\E[?1h\E=:ku=\EOA:le=^H:mb=\E[5m:md=\E[1m:me=\E[0m:\
		:mh=\E[2m:mr=\E[7m:nd=\E[C:nw=\EE:rc=\E8:\
		:rs=\Ec\E[?1000l\E[?25h:\
		:..sa=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;m%?%p9%t\016%e\017%;:\
		:sc=\E7:se=\E[23m:sf=\n:so=\E[3m:sr=\EM:st=\EH:ta=^I:\
		:te=\E[?1049l:ti=\E[?1049h:ue=\E[24m:up=\EM:us=\E[4m:\
		:vb=\Eg:ve=\E[34h\E[?25h:vi=\E[?25l:vs=\E[34l:'
	;;
xterm*)
	TERMCAP="xterm-256color|xterm with 256 colors:"'\
		:am:bs:km:mi:ms:xn:\
		:co#80:it#8:li#24:\
		:AL=\E[%dL:DC=\E[%dP:DL=\E[%dM:DO=\E[%dB:IC=\E[%d@:\
		:K1=\EOw:K2=\EOu:K3=\EOy:K4=\EOq:K5=\EOs:LE=\E[%dD:\
		:RI=\E[%dC:SF=\E[%dS:SR=\E[%dT:UP=\E[%dA:ae=\E(B:al=\E[L:\
		:as=\E(0:bl=^G:bt=\E[Z:cd=\E[J:ce=\E[K:cl=\E[H\E[2J:\
		:cm=\E[%i%d;%dH:cr=\r:cs=\E[%i%d;%dr:ct=\E[3g:dc=\E[P:\
		:dl=\E[M:do=\n:ec=\E[%dX:ei=\E[4l:ho=\E[H:im=\E[4h:\
		:is=\E[!p\E[?3;4l\E[4l\E>:k1=\EOP:k2=\EOQ:k3=\EOR:\
		:k4=\EOS:k5=\E[15~:k6=\E[17~:k7=\E[18~:k8=\E[19~:\
		:k9=\E[20~:kD=\E[3~:kI=\E[2~:kN=\E[6~:kP=\E[5~:kb=\177:\
		:kd=\EOB:ke=\E[?1l\E>:kh=\EOH:kl=\EOD:kr=\EOC:\
		:ks=\E[?1h\E=:ku=\EOA:le=^H:mb=\E[5m:md=\E[1m:me=\E[0m:\
		:mh=\E[2m:mm=\E[?1034h:mo=\E[?1034l:mr=\E[7m:nd=\E[C:\
		:nw=\EE:rc=\E8:..rp=%p1%c\E[%p2%{1}%-%db:\
		:..sa=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m:\
		:sc=\E7:se=\E[27m:sf=\n:so=\E[7m:sr=\EM:st=\EH:ta=^I:\
		:te=\E[?1049l\E[23;0;0t:ti=\E[?1049h\E[22;0;0t:\
		:ue=\E[24m:up=\E[A:us=\E[4m:vb=\E[?5h\E[?5l:\
		:ve=\E[?12l\E[?25h:vi=\E[?25l:vs=\E[?12;25h:'
	;;
*)
	command -v infocmp && TERMCAP=$(infocmp -CT $TERM | grep -v '^#')
esac
export TERMCAP

exec ex -v "$@"

